services:
  app:
    build:
      context: .
      dockerfile: DockerfileApi
    container_name: marketplace-api 
    working_dir: /app 
    volumes:
      - .:/app  # Mount the source code for live synchronization (hot reload)
      - /app/node_modules  # Prevent conflicts with local node_modules
    ports:
      - "3002:3002"
    command: npm run start:dev 

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    profiles: ["ollama"]

volumes:
  ollama_data: