services:
  app:
    build: .
    container_name: marketplace-api 
    working_dir: /app 
    volumes:
      - .:/app  # Mount the source code for live synchronization (hot reload)
      - /app/node_modules  # Prevent conflicts with local node_modules
    ports:
      - "3002:3002"
    command: npm run start:dev 
