services:
  app:
    build: .
    container_name: nest-dev
    working_dir: /app
    volumes:
      - .:/app  # Monta el código fuente para sincronización
      - /app/node_modules  # Evita problemas con node_modules locales
    ports:
      - "3002:3002"
    command: npm run start:dev  # Inicia el servidor en modo de desarrollo
