export interface MarketingLLMResponse {
  /**
   * The full insight or summary generated by the LLM (e.g., Mistral).
   * This is a natural language text that answers the user's prompt.
   */
  insight: string;
}
