export const CITY_ALIASES: Record<string, string[]> = {
  Barcelona: [
    'barcelona',
    'bcn',
    'ciudad condal',
    'barna',
    'barcelonés',
    'barcelonesa',
    'barceloneta',
  ],
  Roma: [
    'roma',
    'roma ciudad',
    'ciudad de roma',
    'rome',
    'romana',
    'romano',
    'capital italiana',
  ],
  París: [
    'parís',
    'paris',
    'ciudad de la luz',
    'capital francesa',
    'parisina',
    'parisino',
    'parís ciudad',
  ],
  Madrid: [
    'madrid',
    'capital de españa',
    'madrileña',
    'madrileño',
    'villa y corte',
    'madrid ciudad',
  ],
  Praga: [
    'praga',
    'prague',
    'ciudad dorada',
    'capital checa',
    'praguense',
    'praga ciudad',
  ],
};

export const VENUE_ALIASES: Record<string, string[]> = {
  'Sagrada Familia': [
    'sagrada familia',
    'iglesia sagrada familia',
    'templo expiatorio de la sagrada familia',
    'templo sagrada familia',
    'basilica sagrada familia',
    'basilica de la sagrada familia',
    'sagrada familia barcelona',
    'sagrada familia gaudí',
    'sagrada familia de gaudí',
  ],
  Coliseo: [
    'coliseo',
    'coliseo romano',
    'colosseum',
    'anfiteatro flavio',
    'coliseo de roma',
    'coliseo en roma',
    'coliseum',
  ],
  'Torre Eiffel': [
    'torre eiffel',
    'eiffel',
    'torre de eiffel',
    'torre paris',
    'eiffel tower',
    'torre de parís',
    'torre eiffel parís',
  ],
  'Museo del Prado': [
    'museo del prado',
    'el prado',
    'prado',
    'museo prado',
    'museo nacional del prado',
    'prado madrid',
    'museo en madrid',
  ],
  'Castillo de Praga': [
    'castillo de praga',
    'prague castle',
    'hradčany',
    'castillo praga',
    'castillo en praga',
    'castillo checo',
  ],
};

export const ACTIVITY_ALIASES: Record<string, string[]> = {
  'Entrada general Sagrada Familia': [
    'entrada general sagrada familia',
    'entrada sagrada familia',
    'visita sagrada familia',
    'ticket sagrada familia',
    'boletos sagrada familia',
    'acceso sagrada familia',
    'entrada a la sagrada familia',
    'entrada general a la sagrada familia',
    'visitar sagrada familia',
    'tour sagrada familia',
    'sagrada familia entrada general',
    'sagrada familia ticket',
    'sagrada familia boletos',
    'sagrada familia acceso',
  ],
  'Visita guiada Coliseo + Foro': [
    'visita guiada coliseo',
    'visita guiada foro',
    'visita guiada coliseo y foro',
    'tour coliseo',
    'tour foro romano',
    'coliseo foro romano',
    'coliseo visita guiada',
    'foro visita guiada',
    'coliseo y foro visita guiada',
    'coliseo + foro',
    'coliseo y foro',
    'coliseo tour',
    'foro tour',
    'entrada coliseo y foro',
    'entrada coliseo + foro',
  ],
  'Acceso prioritario Torre Eiffel': [
    'acceso prioritario torre eiffel',
    'entrada rápida torre eiffel',
    'entrada sin colas torre eiffel',
    'torre eiffel acceso prioritario',
    'torre eiffel entrada rápida',
    'torre eiffel sin colas',
    'torre eiffel acceso rápido',
    'torre eiffel entrada preferente',
    'acceso rápido torre eiffel',
    'acceso preferente torre eiffel',
    'entrada torre eiffel sin colas',
    'ticket rápido torre eiffel',
  ],
  'Entrada + guía Museo del Prado': [
    'entrada museo del prado',
    'entrada + guía museo del prado',
    'entrada con guía museo del prado',
    'museo del prado con guía',
    'visita guiada museo del prado',
    'tour museo del prado',
    'museo del prado tour',
    'museo del prado visita guiada',
    'museo del prado entrada y guía',
    'guía museo del prado',
    'museo prado entrada y guía',
    'entrada y guía prado',
  ],
  'Tour histórico Castillo de Praga': [
    'tour castillo de praga',
    'tour histórico castillo de praga',
    'visita guiada castillo de praga',
    'castillo de praga tour',
    'castillo de praga visita guiada',
    'castillo praga tour',
    'castillo praga visita guiada',
    'tour histórico praga',
    'tour castillo praga',
    'entrada castillo de praga',
    'entrada castillo praga',
    'visita castillo de praga',
  ],
};
